repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: ^vscode-extension/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^vscode-extension/(node_modules|out)/
      - id: trailing-whitespace
        exclude: ^vscode-extension/(node_modules|out)/
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
